
PcmtETBundle\Entity\ReferenceData\EtCountryCode:
    type: entity
    table: pcmt_custom_et_country_code
    changeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    fields:
        id: # required
            type: integer
            id: true
            generator:
                strategy: AUTO
        code: # required
            type: string
            length: 255
            unique: true
        sortOrder: # required
            type: integer
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
