PcmtCISBundle\Entity\Subscription:
    constraints:
        - PcmtCISBundle\Constraint\RequiredFieldConstraint: ~

    properties:
        dataRecipientsGLN:
            - NotBlank: ~
            - GreaterThanOrEqual: 0
            - Type:
                  type: integer
                  message: The value {{ value }} is not a valid {{ type }}.
        dataSourcesGLN:
            - NotBlank: ~
            - GreaterThanOrEqual: 0
            - Type:
                  type: integer
                  message: The value {{ value }} is not a valid {{ type }}.
        GTIN:
            - GreaterThanOrEqual: 0
            - Type:
                  type: integer
                  message: The value {{ value }} is not a valid {{ type }}.
