######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

############### Ethiopia i Environment ###############

.env-ethiopia-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: ethiopia-demo
    url: http://ethiopia-demo.productcatalog.io
    on_stop: env-ethiopia-demo-destroy

.env-ethiopia-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh ethiopia-demo
    
.env-ethiopia-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh ethiopia-demo destroy -auto-approve

env-ethiopia-demo (WIPE DB):
  extends:
    - .env-ethiopia-demo
    - .env-ethiopia-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '1.1.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.1.0/pcmt-v1.1.0.tar.gz'

env-ethiopia-demo (KEEP DB):
  extends:
    - .env-ethiopia-demo
    - .env-ethiopia-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: '1.1.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.1.0/pcmt-v1.1.0.tar.gz'

env-ethiopia-demo-destroy:
  extends:
    - .env-ethiopia-demo
    - .env-ethiopia-demo_script-destroy
  environment:
    name: ethiopia-demo
    action: stop

############### Rwanda Demo Environment ###############

.env-rwanda-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: rwanda-demo
    url: http://rwanda-demo.productcatalog.io
    on_stop: env-rwanda-demo-destroy

.env-rwanda-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh rwanda-demo
    
.env-rwanda-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh rwanda-demo destroy -auto-approve

env-rwanda-demo (WIPE DB):
  extends:
    - .env-rwanda-demo
    - .env-rwanda-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '1.1.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.1.0/pcmt-v1.1.0.tar.gz'

env-rwanda-demo (KEEP DB):
  extends:
    - .env-rwanda-demo
    - .env-rwanda-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: '1.1.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.1.0/pcmt-v1.1.0.tar.gz'

env-rwanda-demo-destroy:
  extends:
    - .env-rwanda-demo
    - .env-rwanda-demo_script-destroy
  environment:
    name: rwanda-demo
    action: stop

############### Demo Environment ###############

.env-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: demo
    url: http://demo.productcatalog.io
    on_stop: env-demo-destroy

.env-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh demo
    
.env-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh demo destroy -auto-approve

env-demo (WIPE DB):
  extends:
    - .env-demo
    - .env-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '2.2.1'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v2.2.1/pcmt-v2.2.1.tar.gz'

env-demo (KEEP DB):
  extends:
    - .env-demo
    - .env-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: '2.2.1'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v2.2.1/pcmt-v2.2.1.tar.gz'

env-demo-scheduled-reset:
  extends:
    - 'env-demo (WIPE DB)'
  only:
    refs:
      - schedules
    variables:
      - $CI_JOB_NAME == "env-demo-scheduled-reset"
  
env-demo-destroy:
  extends:
    - .env-demo
    - .env-demo_script-destroy
  environment:
    name: demo
    action: stop


############### UNDP Demo Environment ###############

.env-undp-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: undp-demo
    url: http://undp-demo.productcatalog.io
    on_stop: env-undp-demo-destroy

.env-undp-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh undp-demo
    
.env-undp-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh undp-demo destroy -auto-approve

env-undp-demo (WIPE DB):
  extends:
    - .env-undp-demo
    - .env-undp-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '2.0.3'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v2.0.3/pcmt-v2.0.3.tar.gz'

env-undp-demo (KEEP DB):
  extends:
    - .env-undp-demo
    - .env-undp-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: '2.0.3'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v2.0.3/pcmt-v2.0.3.tar.gz'

env-undp-demo-destroy:
  extends:
    - .env-undp-demo
    - .env-undp-demo_script-destroy
  environment:
    name: undp-demo
    action: stop

############### Zambia Demo Environment ###############

.env-zambia-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: zambia-demo
    url: http://zambia-demo.productcatalog.io
    on_stop: env-zambia-demo-destroy

.env-zambia-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh zambia-demo
    
.env-zambia-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh zambia-demo destroy -auto-approve

env-zambia-demo (WIPE DB):
  extends:
    - .env-zambia-demo
    - .env-zambia-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '2.0.3'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v2.0.3/pcmt-v2.0.3.tar.gz'

env-zambia-demo (KEEP DB):
  extends:
    - .env-zambia-demo
    - .env-zambia-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: '2.0.3'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v2.0.3/pcmt-v2.0.3.tar.gz'

env-zambia-demo-destroy:
  extends:
    - .env-zambia-demo
    - .env-zambia-demo_script-destroy
  environment:
    name: zambia-demo
    action: stop

############### COVID-dev Environment ###############

.env-covid-dev:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: covid-dev
    url: http://covid-dev.productcatalog.io
    on_stop: env-covid-dev-destroy

.env-covid-dev_script-deploy:
  script:
    - ./bin/ci-deploy.sh covid-dev
    
.env-covid-dev_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh covid-dev destroy -auto-approve

env-covid-dev (WIPE DB):
  extends:
    - .env-covid-dev
    - .env-covid-dev_script-deploy
  variables:
    PCMT_PROFILE: dev

env-covid-dev (KEEP DB):
  extends:
    - .env-covid-dev
    - .env-covid-dev_script-deploy
  variables:
    PCMT_PROFILE: production

env-covid-dev-destroy:
  extends:
    - .env-covid-dev
    - .env-covid-dev_script-destroy
  environment:
    name: covid-dev
    action: stop
