PcmtETBundle\Entity\ReferenceData\Manufacturer:
    properties:
        code:
            - NotBlank: ~
        name:
            - NotBlank: ~

PcmtETBundle\Entity\ReferenceData\EtBrand:
    properties:
        code:
            - NotBlank: ~
        name:
            - NotBlank: ~
