datagrid:
    manufacturer:
        options:
            entityHint: manufacturer
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: PcmtETBundle\Entity\ReferenceData\Manufacturer
            repository_method: createDataGridQueryBuilder
        columns:
            code:
                label: Code
            name:
                label: Name
            countryoforigin:
                label: Country of origin
            address:
                label: Address
            sn:
                label: S/N
            gln:
                label: GLN

        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_rest_get
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_rest_delete
                params:
                    - id
                    - customEntityName
        
        actions:
            edit:
                type:      navigate
                label:     pcmt_custom.Manufacturer.this.edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type: delete
                label: pcmt_custom.Manufacturer.this.delete
                icon: trash
                link: delete_link

        filters:
            columns:
                code:
                    type: string
                    label: code
                    data_name: rd.code
                name:
                    type: search
                    label: Name
                    data_name: rd.name
                address:
                    type: search
                    label: Address
                    data_name: rd.address

        sorters:
            columns:
                code:
                    data_name: rd.code
                name:
                    data_name: rd.name
                countryoforigin:
                    data_name: rd.countryoforigin
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'


        mass_actions:
            delete:
                type: delete
                label: pim.grid.mass_action.delete
                entity_name: manufacturer
                acl_resource: ~
                handler: mass_delete
                className: 'AknButton AknButton--important AknButtonList-item'
                messages:
                    confirm_title: pim_datagrid.mass_action.delete.confirm_title
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: pim_datagrid.mass_action.delete.confirm_ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection

            quick_export_csv:
                type: export
                label: Quick export
                className:  'AknButton AknButton--action AknButtonList-item'
                handler: custom_quick_export
                route: pim_customentity_quickexport
                route_parameters:
                    customEntityName: manufacturer
                    _format: csv
                    _contentType: text/csv
                context:
                    withHeader: true
                messages:
                    empty_selection: Empty selection
