pcmt_rules_execution_index:
  path: /

#pcmt_rules_execution_download_log:
#  path: /{id}/download
#  defaults: { _controller: pim_import_export.controller.import_execution:downloadLogFileAction }
#  requirements:
#    id: \d+

pcmt_rules_execution_show:
  path: /{id}
  requirements:
    id: \d+
