services:

    pcmt.rules.job.constraint_collection_provider.rule_process:
        class: PcmtRulesBundle\Connector\Job\ConstraintCollectionProvider\RuleProcessConstraintCollectionProvider
        arguments:
            -
                - 'pcmt_rule_process'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pcmt.rules.job.constraint_collection_provider.select_options:
        class: PcmtRulesBundle\Connector\Job\ConstraintCollectionProvider\SelectOptionsConstraintCollectionProvider
        arguments:
            -
                - 'pcmt_select_options_rule'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pcmt.rules.job.constraint_collection_provider.pull_images:
        class: PcmtRulesBundle\Connector\Job\ConstraintCollectionProvider\PullImagesConstraintCollectionProvider
        arguments:
            -
                - 'pcmt_pull_images_rule'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }