######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################
parameters:
    pcmt.entity.rule.class:  PcmtRulesBundle\Entity\Rule
    pim_datagrid.event_listener.add_username_to_grid_listener.class: PcmtRulesBundle\Listener\AddUsernameToGridListener

services:

    pcmt.rule.normalizer:
        class: PcmtRulesBundle\Normalizer\RuleNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 80 }

    pcmt.repository.rule:
        class: PcmtRulesBundle\Repository\RuleRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pcmt.entity.rule.class%']
        tags:
            - { name: 'pim_repository' }

    pcmt.remover.rule:
        class: '%pim_catalog.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pcmt.entity.rule.class%'

    pcmt.service.rule_attribute_provider:
        class: PcmtRulesBundle\Service\RuleAttributeProvider
        arguments:
            - '@pim_catalog.repository.attribute'

    pcmt.constraints.attribute_exists_in_both_families_constraint_validator:
        class: PcmtRulesBundle\Validators\AttributeExistsInBothFamiliesConstraintValidator
        arguments:
            - '@pcmt.service.rule_attribute_provider'
        tags:
            - { name: validator.constraint_validator, alias: pcmt_attribute_exists_in_both_families_constraint_validator }

    pcmt.constraints.different_family_constraint_validator:
        class: PcmtRulesBundle\Validators\DifferentFamilyConstraintValidator
        tags:
            - { name: validator.constraint_validator, alias: pcmt_attribute_different_family_constraint_validator }

    pcmt.service.rule_product_processor:
        class: PcmtRulesBundle\Service\RuleProcessor
        arguments:
            - '@pim_enrich.query.product_and_product_model_query_builder_from_size_factory'
            - '@pcmt.service.rule_attribute_provider'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.saver.product_model'
            - '@pim_catalog.builder.product'
            - '@pcmt.service.rule_processor_copier'

    pcmt.service.rule_processor_copier:
        class: PcmtRulesBundle\Service\RuleProcessorCopier
        arguments:
            - '@pim_catalog.updater.property_copier'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - '@pim_enrich.filter.product_attribute_filter'
            - '@pim_enrich.filter.product_model_attribute_filter'
            - '@pim_internal_api_serializer'



