######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################
parameters:
    pim_datagrid.event_listener.add_username_to_grid_listener.class: PcmtRulesBundle\Listener\AddUsernameToGridListener

services:
    pcmt.service.rule_attribute_provider:
        class: PcmtRulesBundle\Service\RuleAttributeProvider
        arguments:
            - '@pim_catalog.repository.attribute'

    pcmt.service.rule_product_processor:
        class: PcmtRulesBundle\Service\RuleProcessor
        arguments:
            - '@pim_enrich.query.product_and_product_model_query_builder_from_size_factory'
            - '@pcmt.service.rule_attribute_provider'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.saver.product_model'
            - '@pim_catalog.builder.product'
            - '@pcmt.service.rule_processor_copier'

    pcmt.service.rule_processor_copier:
        class: PcmtRulesBundle\Service\RuleProcessorCopier
        arguments:
            - '@pim_catalog.updater.property_copier'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - '@pim_enrich.filter.product_attribute_filter'
            - '@pim_enrich.filter.product_model_attribute_filter'
            - '@pim_internal_api_serializer'

    pcmt_rules.datagrid.provider.job:
        class: PcmtRulesBundle\Provider\PcmtJobDatagridProvider
        arguments:
            - '@akeneo_batch.job.job_registry'

    pcmt_rules.service.select_options_remover:
        class: PcmtRulesBundle\Service\SelectOptionsRemover
        arguments:
            - '@pim_catalog.remover.attribute_option'

    pcmt_rules.service.select_options_creator:
        class: PcmtRulesBundle\Service\SelectOptionsCreator
        arguments:
            - '@pim_enrich.query.product_and_product_model_query_builder_from_size_factory'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.factory.attribute_option'
            - '@pim_catalog.saver.attribute_option'

    pcmt_rules.factory.job_notification:
        class: '%pim_import_export.factory.job_notification.class%'
        arguments:
            - [ 'rules' ]
            - '%pim_notification.entity.notification.class%'
        tags:
            - { name: pim_notification.factory.notification }

    pcmt_rules.service.pull_image_service:
        class: PcmtRulesBundle\Service\PullImageService
        arguments:
            - '%tmp_storage_dir%'
            - '@akeneo_file_storage.file_storage.file.file_storer'
            - '@pcmt_rules.service.image_verification_service'

    pcmt_rules.service.update_image_service.product:
        class: PcmtRulesBundle\Service\UpdateImageService
        arguments:
            - '@pim_catalog.updater.product'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.validator.product'

    pcmt_rules.service.update_image_service.product_model:
        class: PcmtRulesBundle\Service\UpdateImageService
        arguments:
            - '@pim_catalog.updater.product_model'
            - '@pim_catalog.saver.product_model'
            - '@pim_catalog.validator.product_model'
            -
    pcmt_rules.service.attributes_level_validator:
        class: PcmtRulesBundle\Service\AttributesLevelValidator

    pcmt_rules.service.image_verification_service:
        class: PcmtRulesBundle\Service\ImageVerificationService

